name: ImageMapRenderer
version: '${project.version}'
main: net.lukesmp.imagemaprenderer.ImageMapRenderer
api-version: 1.19
authors: [ CalcWIZ ]
description: A SpigotMC plugin that can take images from the internet and renders them on in-game maps
website: https://www.lukesmp.net
commands:
  map:
    usage: /map <width> <height> <link> <frame type>
    description: Renders an image on a map
    permission: imagemaprenderer.map
#  invisible:
#    usage: /invisible
#    description: Makes a map invisible
#    permission: imagemaprenderer.invisible
permissions:
  imagemaprenderer.map:
    description: allows player to run the /map command
    default: true
#  imagemaprenderer.invisible:
#    description: allows player to run the /invisible command
#    default: true
  imagemaprenderer.itemFrames:
    description: allows player to receive Item Frames when they render map(s)
    default: true
  imagemaprenderer.glowItemFrames:
    descriptions: allows player to receive Glow Item Frames when they render map(s)
    default: true
